### PR TITLE
Meson build fixes 2

### PR DESCRIPTION
**Pull request by gasinvein**
Allow building vkBasalt with system-wide installed SPIRV via corresponding option (e.g. `-Dspirv_dir=/usr`).
The second commit is mostly cosmetic.

### CODE REVIEW

**Comment by gasinvein** [comment]
Merged current master with reformatted source, hopefully fixing merge conflict in DadSchoorse/vkBasalt#62

**Comment by mcoffin** [comment]
Sorry I haven't had time to look at this. I'll try to get to it this evening.

**Comment by gasinvein** [comment]
The only really meaningful commit here is 48d47db

**Comment by mcoffin** [comment]
@gasinvein With this update, I'm now getting this output with the Makefile (during the configuration step for the 32-bit build).

```
meson --buildtype release --prefix /home/mcoffin/.local --libdir=lib32 --pkg-config-path /usr/lib32/pkgconfig --cross-file meson-32-cross.txt build/Release32
The Meson build system
Version: 0.53.1
Source dir: /home/mcoffin/projects/vkbasalt
Build dir: /home/mcoffin/projects/vkbasalt/build/Release32
Build type: cross build
Project name: vkBasalt
Project version: 0.0.4
Appending LDFLAGS from environment: ['-fuse-ld=gold']
C++ compiler for the build machine: c++ (gcc 9.2.0 "c++ (GCC) 9.2.0")
C++ linker for the build machine: c++ GNU ld.bfd 2.34
C++ compiler for the host machine: g++ (gcc 9.2.0 "g++ (GCC) 9.2.0")
C++ linker for the host machine: g++ GNU ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: x86
Target machine cpu family: x86
Target machine cpu: x86
Found Pkg-config: NO
Run-time dependency vulkan found: NO (tried system)

src/meson.build:3:0: ERROR: Pkg-config binary for machine MachineChoice.HOST not found. Giving up.
```

**Comment by mcoffin** [comment]
Actually, never mind looks like something changed with my setup. I'll look into it.

**Comment by gasinvein** [comment]
I'm testing this in Arch and Ubuntu 19.10 containers. Did stumble on this error before on Arch, but I don't really remember how I've fixed it. Probably by installing `lib32-vulkan`?

**Comment by gasinvein** [comment]
UPD: yes, it's `lib32-vulkan-icd-loader`.

**Comment by mcoffin** [comment]
Yeppers, confirmed that was the issue and merged, thanks

**Pull request merged**
